"""Remove columns.

Revision ID: 18ee3db1ad5e
Revises: 7abcd21413e6
Create Date: 2017-12-20 18:22:32.395353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ee3db1ad5e'
down_revision = '7abcd21413e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('pitch_categories', 'promotion')
    op.drop_column('pitch_categories', 'product')
    op.drop_column('pitch_categories', 'pick_up_lines')
    op.drop_column('pitch_categories', 'interview')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('interview', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitch_categories', sa.Column('pick_up_lines', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitch_categories', sa.Column('product', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitch_categories', sa.Column('promotion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitch_categories', 'name')
    # ### end Alembic commands ###
