"""Create new column.

Revision ID: 2cdcb47ad22f
Revises: 
Create Date: 2017-12-20 21:36:08.035158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdcb47ad22f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', sa.String(length=255), nullable=True))
    op.drop_column('comment', 'section_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('section_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comment', 'comment_id')
    # ### end Alembic commands ###
