"""Add new user.

Revision ID: 5051beeca5d0
Revises: cbdf363b9d25
Create Date: 2017-12-21 10:12:16.887027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5051beeca5d0'
down_revision = 'cbdf363b9d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_categories', 'image')
    # ### end Alembic commands ###
