"""Add columns

Revision ID: 7abcd21413e6
Revises: ab56305144cc
Create Date: 2017-12-20 18:19:02.182631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abcd21413e6'
down_revision = 'ab56305144cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('interview', sa.String(length=255), nullable=True))
    op.add_column('pitch_categories', sa.Column('pick_up_lines', sa.String(length=255), nullable=True))
    op.add_column('pitch_categories', sa.Column('product', sa.String(length=255), nullable=True))
    op.add_column('pitch_categories', sa.Column('promotion', sa.String(length=255), nullable=True))
    op.drop_column('pitch_categories', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitch_categories', 'promotion')
    op.drop_column('pitch_categories', 'product')
    op.drop_column('pitch_categories', 'pick_up_lines')
    op.drop_column('pitch_categories', 'interview')
    # ### end Alembic commands ###
