"""Add description column in category table.

Revision ID: 84d9c45df3a8
Revises: d92377df213e
Create Date: 2017-12-22 16:22:13.472054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d9c45df3a8'
down_revision = 'd92377df213e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_categories', 'description')
    # ### end Alembic commands ###
