"""Remove a column from pitch category and added four category names.

Revision ID: 8885f064ad0b
Revises: 6de3469baaac
Create Date: 2017-12-20 08:49:43.860325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8885f064ad0b'
down_revision = '6de3469baaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_categories', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
