"""Create new columns in category.

Revision ID: c131ca45dff1
Revises: 63f293ec01aa
Create Date: 2017-12-20 19:48:10.948054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c131ca45dff1'
down_revision = '63f293ec01aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('actual_pitch', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'pitch_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'date_posted')
    op.drop_column('pitches', 'category_id')
    op.drop_column('pitches', 'actual_pitch')
    # ### end Alembic commands ###
