"""Remove column in category table

Revision ID: d92377df213e
Revises: eb1221bfe45e
Create Date: 2017-12-22 12:21:18.315037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92377df213e'
down_revision = 'eb1221bfe45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_categories', 'picture_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('picture_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
