"""Add column for picture path in pitch categories.

Revision ID: eb1221bfe45e
Revises: 945747416fed
Create Date: 2017-12-22 10:40:18.351480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1221bfe45e'
down_revision = '945747416fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('picture_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_categories', 'picture_path')
    # ### end Alembic commands ###
